(()=>{const pages=document.getElementById('pages'),dots=[...document.querySelectorAll('.dot')],title=document.getElementById('pageTitle');let page=0,startX=0,dragging=false;
function go(n){page=Math.max(0,Math.min(3,n));pages.style.transform=`translateX(-${page*25}%)`;dots.forEach((d,i)=>d.classList.toggle('active',i===page));title.textContent=document.querySelectorAll('.page')[page].dataset.title;}
document.getElementById('prevBtn').onclick=()=>go(page-1);document.getElementById('nextBtn').onclick=()=>go(page+1);document.getElementById('homeBtn').onclick=()=>go(0);dots.forEach((d,i)=>d.onclick=()=>go(i));
pages.addEventListener('touchstart',e=>{startX=e.touches[0].clientX;dragging=true},{passive:true});pages.addEventListener('touchend',e=>{if(!dragging)return;let dx=e.changedTouches[0].clientX-startX;if(Math.abs(dx)>55)go(page+(dx<0?1:-1));dragging=false},{passive:true});
pages.addEventListener('mousedown',e=>{startX=e.clientX;dragging=true});window.addEventListener('mouseup',e=>{if(!dragging)return;let dx=e.clientX-startX;if(Math.abs(dx)>70)go(page+(dx<0?1:-1));dragging=false});
function clock(){document.getElementById('clock').textContent=new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}clock();setInterval(clock,1000);
const codeText=c=>c===0?'Clear':[1,2].includes(c)?'Partly cloudy':c===3?'Cloudy':[45,48].includes(c)?'Foggy':[51,53,55,61,63,65,80,81,82].includes(c)?'Rain':[71,73,75,77,85,86].includes(c)?'Snow':[95,96,99].includes(c)?'Storms':'Forecast';
const codeIcon=(c,d)=>c===0?(d?'☀️':'🌙'):[1,2].includes(c)?'⛅':c===3?'☁️':[45,48].includes(c)?'🌫️':[51,53,55,61,63,65,80,81,82].includes(c)?'🌧️':[71,73,75,77,85,86].includes(c)?'❄️':[95,96,99].includes(c)?'⛈️':'🌤️';
fetch('https://api.open-meteo.com/v1/forecast?latitude=38.2004&longitude=-84.8776&current=temperature_2m,weather_code,is_day&temperature_unit=fahrenheit&timezone=America%2FNew_York',{cache:'no-store'}).then(r=>r.json()).then(j=>{let c=j.current.weather_code;document.getElementById('weatherIcon').textContent=codeIcon(c,j.current.is_day);document.getElementById('temperature').textContent=Math.round(j.current.temperature_2m)+'° '+codeText(c)}).catch(()=>{});
go(0);})();