const STATIONS = [
  {n:1,name:"K-LOVE",logo:"K-LOVE",className:"klove",desc:"Positive & Encouraging",quality:"AAC",streams:["https://maestro.emfcdn.com/stream_for/k-love/web/aac"]},
  {n:2,name:"WayFM",logo:"wayFM",className:"way",desc:"Real Life. Real Hope.",quality:"128",streams:["https://wayfm.streamguys1.com/wayf.mp3","https://wayfm.streamguys1.com/wayp.mp3"]},
  {n:3,name:"99.1 WFMK",logo:"☀ 99.1",className:"sunny",desc:"Michigan's 80s-to-Now Variety",quality:"128",streams:["https://listen.181fm.com/181-theoffice_128k.mp3"]},
  {n:4,name:"Coastal Superhits",logo:"COASTAL",className:"coast",desc:"Beach-Bar Favorites & Superhits",quality:"128",streams:["https://ice2.somafm.com/seventies-128-mp3","https://listen.181fm.com/181-greatoldies_128k.mp3"]},
  {n:5,name:"WAKY 103.5",logo:"WAKY",className:"city",desc:"Kentuckiana's Greatest Classic Hits",quality:"128",streams:["https://streaming.live365.com/a66683","https://listen.181fm.com/181-greatoldies_128k.mp3"]},
  {n:6,name:"The Yacht",logo:"the yacht",className:"yacht",desc:"Smooth Sailing Favorites",quality:"128",relayId:"181-yachtrock",streams:["https://listen.181fm.com/181-yachtrock_128k.mp3"]},
  {n:7,name:"Super 70s",logo:"Totally ’70s",className:"seventies",desc:"The Soundtrack of a Generation",quality:"128",relayId:"181-70s",streams:["https://listen.181fm.com/181-70s_128k.mp3"]},
  {n:8,name:"Awesome 80s",logo:"Totally ’80s",className:"eighties",desc:"The Biggest Hits of the 80s",quality:"128",relayId:"181-awesome80s",streams:["https://listen.181fm.com/181-awesome80s_128k.mp3"]},
  {n:9,name:"Star 90s",logo:"Totally ’90s",className:"nineties",desc:"The 90s Rule",quality:"128",relayId:"181-star90s",streams:["https://listen.181fm.com/181-star90s_128k.mp3"]},
  {n:10,name:"Good Time Oldies",logo:"OLDIES",className:"oldies",desc:"Golden Oldies That Keep Moving",quality:"128",relayId:"181-goodtime",streams:["https://listen.181fm.com/181-goodtime_128k.mp3","https://listen.181fm.com/181-greatoldies_128k.mp3"]},
  {n:11,name:"Drone Zone",logo:"DRONE ZONE",className:"drone",desc:"Ambient & Chill Electronic",quality:"256",somaId:"dronezone",streams:["https://ice3.somafm.com/dronezone-256-mp3","https://ice5.somafm.com/dronezone-256-mp3"]},
  {n:12,name:"Cinema Sounds",logo:"CINEMA",className:"cinema",desc:"Movie Soundtracks & More",quality:"128",streams:["https://kathy.torontocast.com:1825/stream","https://ice2.somafm.com/secretagent-128-mp3"]},
  {n:13,name:"The Breeze",logo:"BREEZE",className:"breeze",desc:"Smooth Jazz for the Road",quality:"128",streams:["https://listen.181fm.com/181-breeze_128k.mp3"]},
  {n:14,name:"Classical",logo:"CLASSICAL",className:"classical",desc:"Essential Orchestral Works",quality:"128",streams:["https://listen.181fm.com/181-classical_128k.mp3"]},
  {n:15,name:"Solo Piano",logo:"SOLO PIANO",className:"piano",desc:"Peaceful Solo Piano",quality:"128",streams:["https://pianosolo.streamguys1.com/live","https://pianosolo.streamguys1.com/live-aac"]},
  {n:16,name:"700 WLW",logo:"700 WLW",className:"talk",desc:"Cincinnati News, Talk & Sports",quality:"AAC",streams:["https://playerservices.streamtheworld.com/api/livestream-redirect/WLWAMAAC.aac","https://playerservices.streamtheworld.com/api/livestream-redirect/WLWAM.mp3"]},
  {n:17,name:"840 WHAS",logo:"840 WHAS",className:"talk",desc:"Louisville News, Weather & Talk",quality:"AAC",streams:["https://playerservices.streamtheworld.com/api/livestream-redirect/WHASAMAAC.aac","https://playerservices.streamtheworld.com/api/livestream-redirect/WHASAM.mp3"]},
  {n:18,name:"Moody Radio",logo:"MOODY",className:"moody",desc:"Christian Talk & Teaching",quality:"128",streams:["https://primary.moodyradiostream.org/radio.mp3"]},
  {n:19,name:"Conservative Talk",logo:"TALK",className:"talk",desc:"Live National Talk Radio",quality:"AAC",streams:["https://playerservices.streamtheworld.com/api/livestream-redirect/KSKYAMAAC.aac","https://playerservices.streamtheworld.com/api/livestream-redirect/WINDAMAAC.aac"]},
  {n:20,name:"DParkRadio",logo:"DPARK",className:"disney",desc:"Park Music, Attractions & Shows",quality:"128",streams:["https://cheetah.streemlion.com/dparkradio"]},
  {n:21,name:"Sorcerer Radio",logo:"SORCERER",className:"resort",desc:"All Disney Music, All Day",quality:"128",streams:["https://26343.live.streamtheworld.com/SP_R3765675_SC"]},
  {n:22,name:"EPCOT Center",logo:"EPCOT",className:"epcot",desc:"Future World Ambience",quality:"128",streams:["https://ice2.somafm.com/missioncontrol-128-mp3"]},
  {n:23,name:"Animal Kingdom",logo:"ANIMAL",className:"animal",desc:"Wild Ambience & Adventure",quality:"128",streams:["https://ice2.somafm.com/earwaves-128-mp3"]},
  {n:24,name:"Holiday Radio",logo:"HOLIDAY",className:"holiday",desc:"Seasonal Favorites",quality:"128",streams:["https://listen.181fm.com/181-xmas_128k.mp3"]},
  {n:25,name:"Disneyland",logo:"DISNEYLAND",className:"land",desc:"Classic Park Atmosphere",quality:"128",streams:["https://ice2.somafm.com/sonicuniverse-128-mp3"]}
];
